---
# First attempt
- hosts: '{{ runon }}'
  vars: 
    host_name: '{{ host_name }}'
    full_host_name: '{{ full_host_name }}'
    memory: '{{ memory }}'
    vpcus: '{{ vcpus }}'
    disk_size: '{{ disk_size }}'
    cloud_init_path: '/srv/nfs/hydrogen/helium/cloudinit'
    cloud_init_isos: '/srv/nfs/hydrogen/helium/cloudinit/isos'
    base_disk: 'fedora-cloud-base.qcow2'
    disk_path: '/srv/zfs/ember/virt/images/'
    ansible_hosts: '/home/okami/code/ansible/image-provisioner/hosts'
  tasks:
    - name: Instantiate image
      command: rsync -a rsync://hydrogen.srv.oxide.one:/base/{{ base_disk }} {{ disk_path }}/{{ host_name }}.qcow2
      become: yes

    - name: Generate new meta-data instance-id
      shell: 'echo instance-id: {{ host_name }} >> {{ cloud_init_path }}/meta-data'
      become: yes

    - name: Generate new meta-data local-hostname
      shell: 'echo local-hostname: {{ full_host_name }} >> {{ cloud_init_path }}/meta-data'
      become: yes

    - name: Generate cloud-init ISO
      command: genisoimage -output {{ cloud_init_isos }}/{{ host_name }}.iso -joliet -volid cidata \
               -r {{ cloud_init_path }}/user-data {{ cloud_init_path }}/meta-data
      become: yes

    - name: Resize disk image
      command: qemu-img resize {{ disk_path }}/{{ host_name }}.qcow2 {{ disk_size }}

    - name: Import the VM
      command: virt-install \
               --name {{ host_name }} \
               --vcpus {{ vcpus }} \
               --memory {{ memory }} \
               --import \
               --network=network:default \
               --disk '{{ disk_path }}/{{ host_name }}'.qcow2,format=qcow2,bus=virtio \
               --disk {{ cloud_init_isos }}/{{ host_name }}.iso,device=cdrom \
               --os-type=linux \
               --os-variant=archlinux \
               --graphics none \
               --noautoconsole
      become: yes

    - name: Eject the cloud-init ISO
      command: virsh change-media {{ host_name }} sda --eject --config
      become: yes

    - name: Delete the cloud-init ISO
      command: rm '{{ cloud_init_isos }}/{{ host_name }}'.iso
      become: yes 

    - name: Remove old meta-data file
      command: rm '{{ cloud_init_path }}/meta-data'
      become: yes

